apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-aware-config
  namespace: helm-aware
  labels:
    app: helm-aware
data:
  # Application configuration
  HOST: "0.0.0.0"
  PORT: "5000"
  DEBUG: "false"
  
  # Logging configuration - set to DEBUG for troubleshooting
  LOG_LEVEL: "DEBUG"
  
  # Kubernetes configuration
  KUBERNETES_SERVICE_HOST: ""
  KUBERNETES_SERVICE_PORT: "" 