apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-aware-config
  namespace: helm-aware
  labels:
    app: helm-aware
data:
  # Application configuration
  HOST: "0.0.0.0"
  PORT: "5000"
  DEBUG: "false"
  
  # Logging configuration
  LOG_LEVEL: "INFO" 