apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-aware-ingress
  namespace: helm-aware
  labels:
    app: helm-aware
  annotations:
    external-dns.alpha.kubernetes.io/target: "alljedis.justdied.com"
spec:
  tls:
    - hosts: 
      - helm-aware.sith.network
  rules:
    - host: helm-aware.sith.network
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: helm-aware
              port:
                number: 80 
