apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-aware
  namespace: helm-aware
  labels:
    app: helm-aware
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-aware-role
  labels:
    app: helm-aware
rules:
  # Read ArgoCD Applications
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch"]
  # Read ArgoCD ApplicationSets
  - apiGroups: ["argoproj.io"]
    resources: ["applicationsets"]
    verbs: ["get", "list", "watch"]
  # Read namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Read pods for health checks
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # Allow managing configmaps in helm-aware namespace
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-aware-role-binding
  labels:
    app: helm-aware
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-aware-role
subjects:
  - kind: ServiceAccount
    name: helm-aware
    namespace: helm-aware 